# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myGitHubApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myGitHubApp
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'JGProgressHUD'

  target 'myGitHubAppTests' do
    inherit! :search_paths
    pod 'Nimble'
    pod 'Nimble-Snapshots'
    pod 'Quick'
  end


end
